version: "3.7"
services:
  logswift-api:
    build:
      context: ./server
      dockerfile: ./docker/Dockerfile.dev
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    networks:
      - logswift

  logswift-consumer:
    build:
      context: ./server
      dockerfile: ./docker/Dockerfile.worker
    depends_on:
      - rabbitmq
      - logswift-api
    volumes:
      - ./server:/app
    networks:
      - logswift

  logswift-client:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./web:/app
    environment:
      - NEXT_PUBLIC_LOGSWIFT_API_URL=http://localhost:3000
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - logswift

  postgres:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data/
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      interval: 10s
      retries: 10
      test: 'pg_isready -U "postgres" -d "log_01"'
      timeout: 2s
    networks:
      - logswift

  meilisearch:
    image: getmeili/meilisearch:v0.28.0
    ports:
      - "7700:7700"
    volumes:
      - ./volumes/meilidata:/meilidata
    environment:
      - MEILI_MASTER_KEY=password
    networks:
      - logswift

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=rabbitmqpassword
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      # - "5000:5673" # Expose this port while running the producer and consumer services locally
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 15s
      retries: 5
    networks:
      - logswift

networks:
  logswift:
