import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta charSet="utf-8" />
      {/* add favicon */}
      <link rel="icon" href="/favicon.ico" />
      <title>LogSwift</title>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
