FROM golang:1.21.4-alpine3.18

WORKDIR /app

COPY .. .

RUN apk add gcc musl-dev
RUN go mod download

RUN go install github.com/githubnemo/CompileDaemon@latest

ENTRYPOINT CompileDaemon -exclude-dir=.git -exclude-dir=docs --build="go build cmd/api/main.go" --command="./main serve"